# Generated by Django 2.0.2 on 2018-02-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_add_calculation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='_occurrences',
            field=models.IntegerField(default=0),
        ),
    ]
